# Generated by Django 4.1.1 on 2023-08-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('massage', models.CharField(blank=True, max_length=350, null=True)),
            ],
        ),
    ]
