# Generated by Django 4.1.1 on 2023-08-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koltech_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contect',
            old_name='massage',
            new_name='message',
        ),
    ]
