"""
Django settings for project_koltech project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from pathlib import Path
import os
from dotenv import load_dotenv
import json
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent

print(BASE_DIR)
GMAIL_EMAIL = json.load(open(str(BASE_DIR.parent)+"/ENV.JSON"))['GMAIL_USER_EMAIL']
print(GMAIL_EMAIL)